project:
  type: website
  output-dir: docs

website:
  title: "BetaDelta Analytics & Research"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - DataViz.qmd
      - mission.qmd  
      - about.qmd
      - contact_us.qmd
      - Social.qmd
    logo: 'BetaDelta_thumb_black.png'
  twitter-card: true
  google-analytics: "G-CE2VLG3CQL"

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

