project:
  type: website
  output-dir: docs

website:
  title: "BetaDelta Analytics & Research"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: coaching.qmd
        text: Coaching
      - href: profile.qmd
        text: Credentials
      - href: blog_page.qmd
        text: Articles
      - get_support.qmd
    right:
      - icon: linkedin
        href: https://www.linkedin.com/company/89757630/
      - icon: twitter
        href: https://twitter.com/BravoLimaDelta
      - icon: reception-4
        href: https://public.tableau.com/app/profile/brian.davidhizar
    logo: 'BetaDelta_thumb_black.png'
     
  twitter-card: true
  google-analytics: "G-CE2VLG3CQL"

format:
  html:
    theme: lux
    css: styles.css
    toc: true
    grid:
      sidebar-width: 150px
      body-width: 1200px
      margin-width: 150px

editor: visual

