project:
  type: website
  output-dir: docs

website:
  title: "BetaDelta Analytics & Research"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - DataViz.qmd
      - about.qmd
      - contact_us.qmd
    right:
      - icon: linkedin
        href: https://www.linkedin.com/company/89757630/
      - icon: twitter
        href: https://twitter.com/BravoLimaDelta
      - icon: reception-4
        href: https://public.tableau.com/app/profile/brian.davidhizar
    logo: 'BetaDelta_thumb_black.png'
     
  twitter-card: true
  google-analytics: "G-CE2VLG3CQL"

format:
  html:
    theme: lux
    css: styles.css
    toc: true
    grid:
      sidebar-width: 300px
      body-width: 900px
      margin-width: 200px

editor: visual

