---
title: "Get bandwidth"
format:
  html:
    theme: lux
    page-layout: full
---
***

Get help with business intelligence and communicating with data visualization. 

##### Bandwidth so you can focus on the important stuff.

We can help you develop visuals, business intelligence dashboards, or reporting to help you monitor your business environment. 

##### Hire us. 

1.  Tell us what you're looking for.
2.  Onboard us with your team or securely collaborate through Google Drive, Microsoft Teams, or Github.
3.  Work with us part-time, asynchronously.

We help business leaders, expanding teams, entrepreneurs, small business owners, marketers, copywriters, graphic designers, investment advisors, non-profit executives, public administrators, insurance professionals, researchers, influencers, etc.

[Create the bandwidth you need!](https://share.hsforms.com/1I8JrOQTdS2SPY59SMnyfNge0x16)

<i class="bi bi-calendar-week-fill" ></i> <input type="button" class="btn btn-info" onclick="location.href='https://calendly.com/brian-davidhizar/30min';" value="Get BANDWIDTH">

***

Don't waste hours teaching yourself how to deliver effective data visualizations.

Position yourself among the professionals in your sphere.

You don't need deep pockets.

***

###### Understand your business.
###### Form your data story.
###### Influence stakeholders.
###### Be understood.
###### Build credibility.
###### One chart at a time.

***

###### Chart better. Lead better.

***

<!--
```{r, warning=FALSE, message=FALSE, echo=FALSE}
library(knitr)
include_url("https://share.hsforms.com/1I8JrOQTdS2SPY59SMnyfNge0x16", height = "880px")
```
-->